### ISSUE TITLE
Non-functional module

### ISSUE THREAD

**Issue by Erdack54** [sinenco/WHMCS-Allopass#1]
Hello, I have a problem with the module, when I try to access the module as a customer (/ index.php? m = allopass) his does not work, its redirects me to the reception of the customer area, you know its can be from because of what?

Excuse me for my English, I use Bing Translator, I'm French.

**Comment by jordandegea** [comment]
Hello, I don't provide support for WHMCS extensions. If you are on WHMCS >6, this extension may be outdated. 
Good luck.
